export const CHANNELS = {
  inspect: "system:inspect",
  systemOpenSponsor: "system:open-sponsor",
  engineRun: "engine:run",
  engineClearData: "engine:clear-data",
  themesList: "themes:list",
  themesActive: "themes:active",
  themesChooseImage: "themes:choose-image",
  themesCreate: "themes:create",
  themesUpdate: "themes:update",
  themesDuplicate: "themes:duplicate",
  themesSelect: "themes:select",
  themesRemove: "themes:remove",
  themesImport: "themes:import",
  themesExport: "themes:export",
  settingsGet: "settings:get",
  settingsUpdate: "settings:update",
  logsReveal: "logs:reveal",
  progress: "engine:progress",
} as const;
